#!/usr/bin/env python3
"""Generate DA-branded Fix & Feature Update Status PDF for March 6, 2026."""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit

OUTPUT = "/Users/danefrederiksen/Desktop/Digital Accomplice/4_Operations/4.3_Processes/daily reports/Daily_Report_2026-03-06_Claude_Code.pdf"

# DA Brand Colors
ORANGE = HexColor("#F8901E")
BLACK = HexColor("#000000")
WHITE = HexColor("#FFFFFF")
GRAY = HexColor("#5A6B7A")
LIGHT_GRAY = HexColor("#F5F5F5")
GREEN = HexColor("#16a34a")
AMBER = HexColor("#d97706")

W, H = letter
MARGIN = 0.75 * inch
CONTENT_W = W - 2 * MARGIN


def draw_header(c, y):
    # Orange header bar
    c.setFillColor(ORANGE)
    c.rect(0, y - 10, W, 50, fill=True, stroke=False)
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(MARGIN, y + 5, "Prospecting Tools — Fix & Feature Update Status")
    c.setFont("Helvetica", 10)
    c.drawRightString(W - MARGIN, y + 5, "March 6, 2026")
    return y - 30


def draw_summary(c, y):
    # Summary box
    c.setFillColor(LIGHT_GRAY)
    c.roundRect(MARGIN, y - 55, CONTENT_W, 50, 6, fill=True, stroke=False)
    c.setFillColor(BLACK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(MARGIN + 12, y - 22, "Summary")
    c.setFont("Helvetica", 10)
    c.setFillColor(GRAY)
    c.drawString(MARGIN + 12, y - 38, "4 of 6 tasks complete. 2 pending user input. All code committed and pushed to GitHub.")
    c.drawString(MARGIN + 12, y - 50, "14 files changed (12 modified, 2 new).")
    return y - 72


def draw_task(c, y, number, title, status, status_color, details):
    """Draw a single task block."""
    # Calculate height needed
    detail_lines = []
    for d in details:
        wrapped = simpleSplit(d, "Helvetica", 9, CONTENT_W - 30)
        detail_lines.extend(wrapped)

    block_h = 28 + len(detail_lines) * 13 + 8

    if y - block_h < 60:
        c.showPage()
        y = H - MARGIN

    # Task header line
    c.setFillColor(BLACK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(MARGIN, y, f"Task {number}: {title}")

    # Status badge
    c.setFillColor(status_color)
    badge_text = status
    tw = c.stringWidth(badge_text, "Helvetica-Bold", 9)
    bx = W - MARGIN - tw - 16
    c.roundRect(bx, y - 3, tw + 16, 16, 4, fill=True, stroke=False)
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(bx + 8, y + 1, badge_text)

    y -= 18

    # Details
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    for line in detail_lines:
        c.drawString(MARGIN + 15, y, line)
        y -= 13

    # Separator
    y -= 4
    c.setStrokeColor(HexColor("#E5E7EB"))
    c.setLineWidth(0.5)
    c.line(MARGIN, y, W - MARGIN, y)
    y -= 12

    return y


def draw_files_section(c, y):
    if y < 200:
        c.showPage()
        y = H - MARGIN

    c.setFillColor(BLACK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(MARGIN, y, "Files Changed (14)")
    y -= 16

    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(ORANGE)
    c.drawString(MARGIN + 10, y, "New Files:")
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    c.drawString(MARGIN + 75, y, "referral-email-outreach.html, referral-email-serve.js")
    y -= 14

    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(ORANGE)
    c.drawString(MARGIN + 10, y, "Modified:")
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    modified = [
        "b2b-outreach.html, b2b-serve.js, b2b-2nd-outreach.html, b2b-2nd-serve.js,",
        "cyber-2nd-outreach.html, cyber-2nd-serve.js, referral-1st-outreach.html, referral-1st-serve.js,",
        "referral-2nd-outreach.html, referral-2nd-serve.js, hub-serve.js, start-all.js"
    ]
    for line in modified:
        c.drawString(MARGIN + 75, y, line)
        y -= 13

    y -= 6
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(ORANGE)
    c.drawString(MARGIN + 10, y, "Commit:")
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    c.drawString(MARGIN + 75, y, '"Add Tool #12 (Referral Partner Emails), draft reply to DM tools, editable LinkedIn URLs"')
    y -= 14
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(ORANGE)
    c.drawString(MARGIN + 10, y, "Repo:")
    c.setFillColor(GRAY)
    c.setFont("Helvetica", 9)
    c.drawString(MARGIN + 75, y, "github.com/danefrederiksen/digital-accomplice-tools (main)")

    return y - 20


def draw_footer(c):
    c.setFillColor(ORANGE)
    c.rect(0, 0, W, 28, fill=True, stroke=False)
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(W / 2, 10, "Digital Accomplice  |  Generated by Claude Code  |  March 6, 2026")


def main():
    c = canvas.Canvas(OUTPUT, pagesize=letter)
    c.setTitle("Prospecting Tools — Fix & Feature Update Status")
    c.setAuthor("Digital Accomplice / Claude Code")

    y = H - MARGIN
    y = draw_header(c, y)
    y -= 10
    y = draw_summary(c, y)
    y -= 8

    # Task 1
    y = draw_task(c, y, 1,
        "Fix Tool #8 Templates (B2B → Cyber)",
        "COMPLETE", GREEN,
        [
            "Verified cyber-email-outreach.html — all templates already use cybersecurity-specific language.",
            "Zero instances of B2B copy found. No changes needed."
        ])

    # Task 2
    y = draw_task(c, y, 2,
        "Build Tool #12 — Referral Partner Emails",
        "COMPLETE", GREEN,
        [
            "Created referral-email-outreach.html (port 3862) with referral-partner-specific email templates.",
            "Templates: initial outreach, follow-up 1, follow-up 2 — all with {name}/{company} variable substitution.",
            "Features: draft reply, search bar, activity feed link, delete buttons, editable template editor.",
            "Daily target: 3 emails/day. Registered in start-all.js, hub-serve.js, and launch.json.",
            "Server verified working — dashboard loads, templates render, prospect flow tested end-to-end."
        ])

    # Task 3
    y = draw_task(c, y, 3,
        "Add Draft Reply to DM Tools #1, #3–#6",
        "COMPLETE", GREEN,
        [
            "Updated 5 server files — added draftReply to ALLOWED_FIELDS + activity logging:",
            "  b2b-serve.js, b2b-2nd-serve.js, cyber-2nd-serve.js, referral-1st-serve.js, referral-2nd-serve.js",
            "Updated 5 HTML files with purple-themed (#6b21a8) draft reply UI:",
            "  b2b-outreach.html, b2b-2nd-outreach.html, cyber-2nd-outreach.html, referral-1st-outreach.html, referral-2nd-outreach.html",
            "Features: auto-generated default reply text, copy-to-clipboard button, debounced auto-save to server."
        ])

    # Task 4
    y = draw_task(c, y, 4,
        "Add Editable LinkedIn URL to Tools #3 and #4",
        "COMPLETE", GREEN,
        [
            "Updated b2b-2nd-outreach.html and cyber-2nd-outreach.html.",
            "Inline editable text input replaces static LinkedIn links. Debounced API save on every edit.",
            "Fallback to LinkedIn search URL when no profile URL is saved.",
            "Works in both Dashboard card view and All Prospects tab."
        ])

    # Task 5
    y = draw_task(c, y, 5,
        "Import Prospect Data (Tools #7–#10, #12)",
        "PENDING", AMBER,
        [
            "Awaiting CSV files from Dane. Import sources:",
            "  Tool #7 — B2B Emails: TBD",
            "  Tool #8 — Cyber Emails: BreachRX, Binary Defense, DirectDefense, CyberMaxx, AgileBlue",
            "  Tool #9 — Substack: 150 subscribers from Substack export",
            "  Tool #10 — Customers: 108 past clients (Twitch, Adobe, BigPanda, Neo4j, etc.)",
            "  Tool #12 — Referral Partners: Deb Andrews/Marketri, Terrie Wheeler/PSM Marketing, Kara Jensen/Bop Design, etc."
        ])

    # Task 6
    y = draw_task(c, y, 6,
        "Handle 7 Overdue Follow-Ups",
        "PENDING", AMBER,
        [
            "Manual browser task — requires Dane to open each tool and action the overdue items.",
            "3 overdue in Cyber 1st Connections (Tool #2, port 3852).",
            "4 overdue in Referral 1st Connections (Tool #5, port 3855)."
        ])

    # Files section
    y = draw_files_section(c, y)

    # Footer
    draw_footer(c)

    c.save()
    print(f"PDF saved to: {OUTPUT}")


if __name__ == "__main__":
    main()
