from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white, black
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus.flowables import KeepTogether

# DA Brand Colors
DA_ORANGE = HexColor("#F8901E")
DA_BLACK = HexColor("#000000")
DA_BLUE_GRAY = HexColor("#5A6B7A")
DA_GRAY = HexColor("#CBCBCB")
DA_LIGHT_GRAY = HexColor("#F5F5F5")
DA_WHITE = HexColor("#FFFFFF")
GREEN = HexColor("#2E7D32")
RED = HexColor("#C62828")
AMBER = HexColor("#F57F17")

output_path = "/Users/danefrederiksen/Desktop/Digital Accomplice/4_Operations/4.3_Processes/daily reports/Daily_Report_2026-03-06_Claude_Code.pdf"

doc = SimpleDocTemplate(
    output_path,
    pagesize=letter,
    topMargin=0.5 * inch,
    bottomMargin=0.6 * inch,
    leftMargin=0.6 * inch,
    rightMargin=0.6 * inch,
)

# Styles
styles = {
    "title": ParagraphStyle(
        "title", fontName="Helvetica-Bold", fontSize=24, textColor=DA_BLACK,
        spaceAfter=2, alignment=TA_LEFT, leading=28
    ),
    "subtitle": ParagraphStyle(
        "subtitle", fontName="Helvetica", fontSize=11, textColor=DA_BLUE_GRAY,
        spaceAfter=1, alignment=TA_LEFT
    ),
    "generated": ParagraphStyle(
        "generated", fontName="Helvetica", fontSize=8, textColor=DA_GRAY,
        spaceAfter=6, alignment=TA_LEFT
    ),
    "section": ParagraphStyle(
        "section", fontName="Helvetica-Bold", fontSize=13, textColor=DA_ORANGE,
        spaceBefore=14, spaceAfter=6, alignment=TA_LEFT
    ),
    "body": ParagraphStyle(
        "body", fontName="Helvetica", fontSize=9, textColor=DA_BLACK,
        spaceAfter=4, alignment=TA_LEFT, leading=13
    ),
    "bullet": ParagraphStyle(
        "bullet", fontName="Helvetica", fontSize=9, textColor=DA_BLACK,
        spaceAfter=3, alignment=TA_LEFT, leading=13, leftIndent=12, bulletIndent=0
    ),
    "numbered": ParagraphStyle(
        "numbered", fontName="Helvetica", fontSize=9, textColor=DA_BLACK,
        spaceAfter=3, alignment=TA_LEFT, leading=13, leftIndent=16, bulletIndent=0
    ),
    "footer": ParagraphStyle(
        "footer", fontName="Helvetica", fontSize=7, textColor=DA_GRAY,
        alignment=TA_CENTER
    ),
    "table_header": ParagraphStyle(
        "th", fontName="Helvetica-Bold", fontSize=8.5, textColor=DA_WHITE, leading=11
    ),
    "table_cell": ParagraphStyle(
        "tc", fontName="Helvetica", fontSize=8.5, textColor=DA_BLACK, leading=11
    ),
    "table_cell_bold": ParagraphStyle(
        "tcb", fontName="Helvetica-Bold", fontSize=8.5, textColor=DA_BLACK, leading=11
    ),
    "table_cell_green": ParagraphStyle(
        "tcg", fontName="Helvetica-Bold", fontSize=8.5, textColor=GREEN, leading=11
    ),
    "table_cell_red": ParagraphStyle(
        "tcr", fontName="Helvetica-Bold", fontSize=8.5, textColor=RED, leading=11
    ),
    "table_cell_amber": ParagraphStyle(
        "tca", fontName="Helvetica-Bold", fontSize=8.5, textColor=AMBER, leading=11
    ),
    "table_cell_white": ParagraphStyle(
        "tcw", fontName="Helvetica-Bold", fontSize=8.5, textColor=DA_WHITE, leading=11
    ),
}

story = []

p = lambda t, s="tc": Paragraph(t, styles.get(s, styles["table_cell"]))

# ── HEADER ──
story.append(Paragraph("DAILY PROSPECTING REPORT", styles["title"]))
story.append(Paragraph("Digital Accomplice  |  March 6, 2026", styles["subtitle"]))
story.append(Paragraph("Generated by Claude Code", styles["generated"]))
story.append(HRFlowable(width="100%", thickness=2, color=DA_ORANGE, spaceAfter=10))

# ── SECTION 1: TODAY'S ACTIVITY ──
story.append(Paragraph("TODAY'S ACTIVITY", styles["section"]))

activity_data = [
    [p("Action Type", "th"), p("Count", "th"), p("Source", "th")],
    [p("New DMs sent"), p("4"), p("B2B 1st Connections")],
    [p("Follow-ups sent"), p("12"), p("B2B 1st Connections")],
    [p("Connection requests"), p("10"), p("7 Cyber 2nd + 3 Referral 2nd")],
    [p("Replies received"), p("1"), p("Brenton Thomas MBA (B2B 1st)")],
    [p("New prospects added"), p("16"), p("11 Cyber 2nd + 5 Referral 2nd")],
    [p("Comments logged"), p("0"), p("—")],
    [p("TOTAL TOUCHES", "tcw"), p("27", "tcw"), p("", "tcw")],
]

col_widths = [2.2 * inch, 0.8 * inch, 3.8 * inch]
t1 = Table(activity_data, colWidths=col_widths, repeatRows=1)
t1.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), DA_BLACK),
    ("TEXTCOLOR", (0, 0), (-1, 0), DA_WHITE),
    ("BACKGROUND", (0, -1), (-1, -1), DA_ORANGE),
    ("ROWBACKGROUNDS", (0, 1), (-1, -2), [DA_WHITE, DA_LIGHT_GRAY]),
    ("GRID", (0, 0), (-1, -1), 0.5, DA_GRAY),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
]))
story.append(t1)

# ── SECTION 2: DAILY TARGETS vs ACTUAL ──
story.append(Paragraph("DAILY TARGETS vs ACTUAL", styles["section"]))

targets_data = [
    [p("Metric", "th"), p("Target", "th"), p("Actual", "th"), p("Status", "th")],
    [p("DMs sent"), p("3-4 new/day"), p("4"), p("ON TARGET", "tcg")],
    [p("Follow-ups"), p("varies"), p("12"), p("STRONG", "tcg")],
    [p("Connection requests"), p("25-40/day"), p("10"), p("BELOW TARGET", "tcr")],
    [p("Comments"), p("8/day"), p("0"), p("MISSED", "tcr")],
    [p("Total touches"), p("45-60/day"), p("27"), p("BELOW TARGET (45%)", "tca")],
]

col_widths2 = [2.0 * inch, 1.5 * inch, 1.0 * inch, 2.3 * inch]
t2 = Table(targets_data, colWidths=col_widths2, repeatRows=1)
t2.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), DA_BLACK),
    ("TEXTCOLOR", (0, 0), (-1, 0), DA_WHITE),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [DA_WHITE, DA_LIGHT_GRAY]),
    ("GRID", (0, 0), (-1, -1), 0.5, DA_GRAY),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
]))
story.append(t2)

# ── SECTION 3: PIPELINE OVERVIEW ──
story.append(Paragraph("PIPELINE OVERVIEW", styles["section"]))

pipeline_data = [
    [p("Tool", "th"), p("Prospects", "th"), p("Active", "th"), p("Not Started", "th")],
    [p("#1 - B2B 1st Connections"), p("35"), p("35"), p("0")],
    [p("#2 - Cyber 1st Connections"), p("11"), p("11"), p("0")],
    [p("#3 - B2B 2nd Connections"), p("14"), p("0"), p("14")],
    [p("#4 - Cyber 2nd Connections"), p("245"), p("8"), p("237")],
    [p("#5 - Referral 1st Connections"), p("55"), p("4"), p("51")],
    [p("#6 - Referral 2nd Connections"), p("30"), p("8"), p("22")],
    [p("#7-10 - Email Tools"), p("0"), p("—"), p("No data imported")],
    [p("Main Dashboard"), p("1,003"), p("6"), p("997")],
    [p("TOTAL", "tcb"), p("1,393", "tcb"), p("72", "tcb"), p("1,321", "tcb")],
]

col_widths3 = [2.6 * inch, 1.2 * inch, 1.2 * inch, 1.8 * inch]
t3 = Table(pipeline_data, colWidths=col_widths3, repeatRows=1)
t3.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), DA_BLACK),
    ("TEXTCOLOR", (0, 0), (-1, 0), DA_WHITE),
    ("ROWBACKGROUNDS", (0, 1), (-1, -2), [DA_WHITE, DA_LIGHT_GRAY]),
    ("BACKGROUND", (0, -1), (-1, -1), DA_LIGHT_GRAY),
    ("GRID", (0, 0), (-1, -1), 0.5, DA_GRAY),
    ("LINEABOVE", (0, -1), (-1, -1), 1.5, DA_ORANGE),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
]))
story.append(t3)

# ── SECTION 4: SEQUENCE STATUS ──
story.append(Paragraph("SEQUENCE STATUS", styles["section"]))

seq_data = [
    [p("Tool", "th"), p("Stage", "th"), p("Count", "th")],
    [p("B2B 1st (#1)"), p("DM sent (awaiting reply)"), p("20")],
    [p("B2B 1st (#1)"), p("In follow-up 1"), p("12")],
    [p("B2B 1st (#1)"), p("Replied"), p("1", "tcg")],
    [p("Cyber 1st (#2)"), p("DM sent (awaiting reply)"), p("3")],
    [p("Cyber 1st (#2)"), p("In follow-up 1"), p("8")],
    [p("Referral 1st (#5)"), p("DM sent"), p("4")],
    [p("Referral 1st (#5)"), p("Replied"), p("1", "tcg")],
    [p("Cyber 2nd (#4)"), p("Connection sent"), p("8")],
    [p("Referral 2nd (#6)"), p("Connection sent"), p("8")],
]

col_widths4 = [2.2 * inch, 2.8 * inch, 1.8 * inch]
t4 = Table(seq_data, colWidths=col_widths4, repeatRows=1)
t4.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), DA_BLACK),
    ("TEXTCOLOR", (0, 0), (-1, 0), DA_WHITE),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [DA_WHITE, DA_LIGHT_GRAY]),
    ("GRID", (0, 0), (-1, -1), 0.5, DA_GRAY),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
]))
story.append(t4)

# ── SECTION 5: ALL-TIME TOTALS ──
story.append(Paragraph("ALL-TIME ENGAGEMENT TOTALS", styles["section"]))

alltime_data = [
    [p("Engagement Type", "th"), p("Count", "th"), p("Breakdown", "th")],
    [p("DMs Sent"), p("54"), p("34 B2B + 13 Cyber + 7 Referral")],
    [p("Follow-Ups Sent"), p("21"), p("12 B2B + 8 Cyber + 1 Referral")],
    [p("Connection Requests"), p("17"), p("1 B2B-2nd + 8 Cyber-2nd + 8 Referral-2nd")],
    [p("Comments Logged"), p("13"), p("Via comment queue across 2nd-conn tools")],
    [p("Replies Received"), p("2", "tcg"), p("1 B2B 1st + 1 Referral 1st", "tcg")],
]

col_widths5 = [2.0 * inch, 0.8 * inch, 4.0 * inch]
t5 = Table(alltime_data, colWidths=col_widths5, repeatRows=1)
t5.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), DA_BLACK),
    ("TEXTCOLOR", (0, 0), (-1, 0), DA_WHITE),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [DA_WHITE, DA_LIGHT_GRAY]),
    ("GRID", (0, 0), (-1, -1), 0.5, DA_GRAY),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
]))
story.append(t5)

# ── SECTION 6: DATA QUALITY FLAGS ──
story.append(Paragraph("DATA QUALITY FLAGS", styles["section"]))

flags = [
    "Cyber 2nd has junk/test entries (\"Name\", \"tool 3 batch 2\", \"REFERRAL\") - clean when convenient",
    "B2B 2nd has title/company fields swapped on ~half of entries from second import batch",
    "Some duplicate names across tools (e.g., Peter Prieto) - expected for different outreach contexts",
    "Email tools (#7-10) have no prospect data imported yet",
]
for f in flags:
    story.append(Paragraph(f"•  {f}", styles["bullet"]))

# ── SECTION 7: KEY TAKEAWAYS ──
story.append(Paragraph("KEY TAKEAWAYS", styles["section"]))

takeaways = [
    "<b>DM volume is on target</b> (4 new + 12 follow-ups). Keep this pace.",
    "<b>Connection requests at 10/day</b> - need to push toward 25-40 range.",
    "<b>Zero comments today</b> - biggest gap. Target is 8/day.",
    "<b>1 reply received today</b> (Brenton Thomas MBA) - follow up promptly.",
    "<b>2 total replies all-time</b> (1 B2B, 1 Referral). Pipeline is starting to produce.",
    "<b>16 new prospects added today</b> (11 Cyber 2nd + 5 Referral 2nd). Pipeline growing.",
    "<b>1,321 prospects still untouched.</b> Huge runway ahead.",
    "<b>Email tools still empty</b> - importing data would unlock 15-28 additional daily touches.",
]
for i, t in enumerate(takeaways, 1):
    story.append(Paragraph(f"{i}.  {t}", styles["numbered"]))

# ── FOOTER ──
story.append(Spacer(1, 20))
story.append(HRFlowable(width="100%", thickness=1, color=DA_GRAY, spaceAfter=6))
story.append(Paragraph(
    "Digital Accomplice  |  Confidential  |  Generated by Claude Code",
    styles["footer"]
))

# Build
doc.build(story)
print(f"PDF saved to: {output_path}")
