#!/usr/bin/env python3
"""Generate DA-branded Fix Plan Progress Report PDF."""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
import os

# DA Brand Colors
ORANGE = HexColor('#F8901E')
BLACK = HexColor('#000000')
BLUE_GRAY = HexColor('#5A6B7A')
GRAY = HexColor('#CBCBCB')
LIGHT_GRAY = HexColor('#F5F5F5')
WHITE = HexColor('#FFFFFF')
RED = HexColor('#c62828')
GREEN = HexColor('#2e7d32')
BLUE = HexColor('#1565c0')

OUTPUT_PATH = "/Users/danefrederiksen/Desktop/Digital Accomplice/4_Operations/4.3_Processes/daily reports/Daily_Report_2026-03-06_Claude_Code.pdf"

# ============================================================
# STYLES
# ============================================================
styles = {
    'title': ParagraphStyle('Title', fontName='Helvetica-Bold', fontSize=22, textColor=BLACK, spaceAfter=2),
    'subtitle': ParagraphStyle('Subtitle', fontName='Helvetica', fontSize=11, textColor=BLUE_GRAY, spaceAfter=4),
    'date': ParagraphStyle('Date', fontName='Helvetica', fontSize=9, textColor=HexColor('#999999'), spaceAfter=12),
    'h2': ParagraphStyle('H2', fontName='Helvetica-Bold', fontSize=14, textColor=ORANGE, spaceBefore=16, spaceAfter=8),
    'h3': ParagraphStyle('H3', fontName='Helvetica-Bold', fontSize=11, textColor=BLACK, spaceBefore=10, spaceAfter=4),
    'body': ParagraphStyle('Body', fontName='Helvetica', fontSize=10, textColor=BLACK, leading=14, spaceAfter=4),
    'body_gray': ParagraphStyle('BodyGray', fontName='Helvetica', fontSize=10, textColor=BLUE_GRAY, leading=14, spaceAfter=4),
    'bullet': ParagraphStyle('Bullet', fontName='Helvetica', fontSize=10, textColor=BLACK, leading=14, leftIndent=18, spaceAfter=2, bulletIndent=6),
    'stat_big': ParagraphStyle('StatBig', fontName='Helvetica-Bold', fontSize=28, textColor=ORANGE, alignment=TA_CENTER),
    'stat_label': ParagraphStyle('StatLabel', fontName='Helvetica', fontSize=9, textColor=BLUE_GRAY, alignment=TA_CENTER, spaceAfter=4),
    'footer': ParagraphStyle('Footer', fontName='Helvetica', fontSize=8, textColor=HexColor('#999999'), alignment=TA_CENTER),
    'badge_done': ParagraphStyle('BadgeDone', fontName='Helvetica-Bold', fontSize=8, textColor=GREEN, alignment=TA_CENTER),
    'table_header': ParagraphStyle('TH', fontName='Helvetica-Bold', fontSize=9, textColor=ORANGE),
    'table_cell': ParagraphStyle('TD', fontName='Helvetica', fontSize=9, textColor=BLACK, leading=12),
    'table_cell_bold': ParagraphStyle('TDBold', fontName='Helvetica-Bold', fontSize=9, textColor=BLACK, leading=12),
}

def build_pdf():
    doc = SimpleDocTemplate(
        OUTPUT_PATH,
        pagesize=letter,
        leftMargin=0.7*inch, rightMargin=0.7*inch,
        topMargin=0.6*inch, bottomMargin=0.6*inch
    )
    story = []

    # ---- Header ----
    story.append(Paragraph("Prospecting Tools Fix Plan", styles['title']))
    story.append(Paragraph("Progress Report &mdash; All Steps Complete", styles['subtitle']))
    story.append(Paragraph("March 6, 2026 &bull; Digital Accomplice &bull; Generated by Claude Code", styles['date']))
    story.append(HRFlowable(width="100%", thickness=3, color=ORANGE, spaceAfter=12))

    # ---- Summary Box ----
    summary_data = [
        [Paragraph('<b>327</b>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=22, textColor=ORANGE, alignment=TA_CENTER)),
         Paragraph('<b>10/10</b>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=22, textColor=GREEN, alignment=TA_CENTER)),
         Paragraph('<b>81</b>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=22, textColor=ORANGE, alignment=TA_CENTER)),
         Paragraph('<b>12</b>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=22, textColor=ORANGE, alignment=TA_CENTER))],
        [Paragraph('Total Prospects', styles['stat_label']),
         Paragraph('Steps Complete', styles['stat_label']),
         Paragraph('Touches This Week', styles['stat_label']),
         Paragraph('Servers Running', styles['stat_label'])],
    ]
    summary_table = Table(summary_data, colWidths=[1.7*inch]*4)
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BLACK),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 12),
        ('ROUNDEDCORNERS', [6, 6, 6, 6]),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 14))

    # ---- Completed Steps Table ----
    story.append(Paragraph("Completed Steps", styles['h2']))

    steps = [
        ('1A', 'P1', 'Remove junk/test records (~80 entries, mostly Tool #4)'),
        ('1B', 'P1', 'Fix cross-tool duplicates (27 between #1 and #5)'),
        ('1C', 'P1', 'Fix swapped company/title fields in Tools #3/#4'),
        ('1D', 'P1', 'Verify data integrity across all tools'),
        ('2A', 'P2', 'Add search bars to all 10 tools'),
        ('2B', 'P2', 'Add activity feed links to all 10 tools'),
        ('2C', 'P2', 'Add delete buttons on dashboard + waiting cards (all 10)'),
        ('2D', 'P2', 'Add editable offer/message template editors (all 10)'),
        ('3',  'P3', 'Verify Tool #11 (Comment Queue) integration end-to-end'),
        ('4',  'P4', 'Build Unified Hub Dashboard (port 3849)'),
    ]

    priority_colors = {'P1': RED, 'P2': ORANGE, 'P3': BLUE, 'P4': BLUE_GRAY}

    header_row = [
        Paragraph('<b>Step</b>', styles['table_header']),
        Paragraph('<b>Priority</b>', styles['table_header']),
        Paragraph('<b>Description</b>', styles['table_header']),
        Paragraph('<b>Status</b>', styles['table_header']),
    ]
    table_data = [header_row]
    for step_num, priority, desc in steps:
        p_color = priority_colors.get(priority, BLUE_GRAY)
        table_data.append([
            Paragraph(f'<b>{step_num}</b>', styles['table_cell_bold']),
            Paragraph(f'<font color="#{p_color.hexval()[2:]}">{priority}</font>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=9, textColor=p_color)),
            Paragraph(desc, styles['table_cell']),
            Paragraph('<font color="#2e7d32"><b>Done</b></font>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=9, textColor=GREEN)),
        ])

    steps_table = Table(table_data, colWidths=[0.5*inch, 0.6*inch, 4.4*inch, 0.6*inch])
    steps_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), LIGHT_GRAY),
        ('GRID', (0, 0), (-1, -1), 0.5, GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, HexColor('#fafafa')]),
    ]))
    story.append(steps_table)
    story.append(Spacer(1, 8))

    # ---- Hub Dashboard Details ----
    story.append(Paragraph("Hub Dashboard (Step 4)", styles['h2']))
    story.append(Paragraph("New unified dashboard on <b>port 3849</b> that reads all 10 tool JSON files and the comment log. Read-only &mdash; no race conditions. Launches automatically with <font face='Courier'>node start-all.js</font>.", styles['body']))

    hub_features = [
        '<b>5 score cards:</b> Touches Today, DMs + Connects, Emails Sent, Comments, Replies &mdash; with progress bars vs daily targets',
        '<b>4 alert types:</b> Overdue follow-ups (with clickable tool links), inactive tools, comment progress, reply celebrations',
        '<b>Quick links:</b> All 11 tools with prospect counts, one-click to open',
        '<b>Per-tool cards:</b> Progress bar, DMs/connections/follow-ups/replies/overdue count, "Open Tool" link',
        '<b>Comment Queue card:</b> Today + week counts, per-segment breakdown',
        '<b>Weekly summary table:</b> All tools with DMs, connects, follow-ups, emails, replies, touches &mdash; TOTAL row',
        '<b>Auto-refresh:</b> Every 30 seconds, plus manual Refresh button',
    ]
    for feat in hub_features:
        story.append(Paragraph(feat, styles['bullet'], bulletText='\u2022'))
    story.append(Spacer(1, 4))

    story.append(Paragraph("Files: <font face='Courier'>hub-serve.js</font> + <font face='Courier'>hub-dashboard.html</font>. DA branded (black header, orange accent, Inter/Arial).", styles['body_gray']))

    # ---- Pipeline Stats ----
    story.append(Paragraph("Current Pipeline Stats", styles['h2']))

    pipeline_data = [
        [Paragraph('<b>Tool</b>', styles['table_header']),
         Paragraph('<b>Prospects</b>', styles['table_header']),
         Paragraph('<b>Touches (Week)</b>', styles['table_header']),
         Paragraph('<b>Status</b>', styles['table_header'])],
        [Paragraph('#1 B2B 1st DM', styles['table_cell']), Paragraph('7', styles['table_cell']), Paragraph('<b>40</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
        [Paragraph('#2 Cyber 1st DM', styles['table_cell']), Paragraph('11', styles['table_cell']), Paragraph('<b>13</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
        [Paragraph('#3 B2B 2nd DM', styles['table_cell']), Paragraph('0', styles['table_cell']), Paragraph('0', styles['table_cell']), Paragraph('<font color="#999999">Empty</font>', styles['table_cell'])],
        [Paragraph('#4 Cyber 2nd DM', styles['table_cell']), Paragraph('221', styles['table_cell']), Paragraph('<b>7</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
        [Paragraph('#5 Referral 1st', styles['table_cell']), Paragraph('58', styles['table_cell']), Paragraph('<b>2</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
        [Paragraph('#6 Referral 2nd', styles['table_cell']), Paragraph('30', styles['table_cell']), Paragraph('<b>8</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
        [Paragraph('#7-#10 Email Tools', styles['table_cell']), Paragraph('0', styles['table_cell']), Paragraph('0', styles['table_cell']), Paragraph('<font color="#999999">No data yet</font>', styles['table_cell'])],
        [Paragraph('#11 Comment Queue', styles['table_cell']), Paragraph('&mdash;', styles['table_cell']), Paragraph('<b>10</b>', styles['table_cell_bold']), Paragraph('Active', styles['table_cell'])],
    ]

    # Total row
    pipeline_data.append([
        Paragraph('<b>TOTAL</b>', styles['table_cell_bold']),
        Paragraph('<b>327</b>', styles['table_cell_bold']),
        Paragraph('<b>81 touches</b>', ParagraphStyle('', fontName='Helvetica-Bold', fontSize=9, textColor=ORANGE)),
        Paragraph('', styles['table_cell']),
    ])

    pipeline_table = Table(pipeline_data, colWidths=[2*inch, 1.1*inch, 1.4*inch, 1.6*inch])
    pipeline_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), LIGHT_GRAY),
        ('GRID', (0, 0), (-1, -1), 0.5, GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [WHITE, HexColor('#fafafa')]),
        ('BACKGROUND', (0, -1), (-1, -1), LIGHT_GRAY),
        ('LINEABOVE', (0, -1), (-1, -1), 2, ORANGE),
    ]))
    story.append(pipeline_table)
    story.append(Spacer(1, 8))

    # ---- Today's Activity Snapshot ----
    story.append(Paragraph("Today's Activity (March 6)", styles['h2']))

    today_items = [
        '<b>26 touches</b> (43% of 60/day target)',
        '<b>4 DMs sent</b> + <b>10 connection requests</b>',
        '<b>12 follow-ups sent</b> (B2B 1st)',
        '<b>3 comments logged</b> (38% of 8/day target)',
        '<b>1 reply received</b>',
        '<font color="#c62828"><b>7 overdue follow-ups</b></font> &mdash; Cyber 1st (3), Referral 1st (4)',
    ]
    for item in today_items:
        story.append(Paragraph(item, styles['bullet'], bulletText='\u2022'))

    # ---- What's Next ----
    story.append(Paragraph("What's Next", styles['h2']))
    story.append(Paragraph("The fix plan is <b>complete</b>. All 10 steps are done and deployed. Here's what comes next:", styles['body']))

    next_items = [
        ('<b>Clear overdue follow-ups</b>', 'Cyber 1st DM has 3 overdue, Referral 1st has 4. Open those tools and send follow-ups or mark cold.'),
        ('<b>Load email tools (#7-#10)</b>', 'B2B Email, Cyber Email, Substack, and Customer tools are built but empty. Import prospect data when ready.'),
        ('<b>Daily Hub check-in</b>', 'Open http://localhost:3849 at start of day to see targets, alerts, and progress. Auto-refreshes every 30s.'),
        ('<b>Hit daily targets</b>', '60 touches/day (30 DMs + 20 emails + 8 comments + connection requests). Hub Dashboard tracks all of it.'),
        ('<b>Friday weekly review</b>', 'Use the Hub\'s Weekly Summary table to review touches, replies, and reply rate for the week.'),
        ('<b>Bonus fixes (low priority)</b>', 'Draft reply on all DM tools (only Tool #2 has it). Editable LinkedIn URLs on Tools #3/#4. Tool #8 templates still reference B2B instead of cyber.'),
    ]
    for title, desc in next_items:
        story.append(Paragraph(f'{title} &mdash; {desc}', styles['bullet'], bulletText='\u2022'))

    # ---- GitHub ----
    story.append(Spacer(1, 12))
    story.append(Paragraph("GitHub", styles['h3']))
    story.append(Paragraph("All changes committed and pushed to <font face='Courier'>github.com/danefrederiksen/digital-accomplice-tools</font> (private). Latest commit: <font face='Courier'>5e0ed46</font>.", styles['body_gray']))

    # ---- Footer ----
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=GRAY, spaceAfter=8))
    story.append(Paragraph("Digital Accomplice &bull; Prospecting Tools Fix Plan &bull; March 6, 2026 &bull; Generated by Claude Code", styles['footer']))

    doc.build(story)
    print(f"PDF saved to: {OUTPUT_PATH}")

if __name__ == '__main__':
    build_pdf()
